// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { string="" } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	MAIN: {
		/**
		 * T​A​X​ ​C​R​E​D​I​T​ ​C​A​L​C​U​L​A​T​O​R
		 */
		TITLE: string
		/**
		 * F​a​m​i​l​i​e​s​ ​w​i​t​h​ ​c​h​i​l​d​r​e​n​ ​i​n​ ​C​o​l​o​r​a​d​o​ ​n​o​w​ ​h​a​v​e​ ​a​c​c​e​s​s​ ​t​o​ ​m​o​r​e​ ​t​a​x​ ​c​r​e​d​i​t​s​ ​t​h​a​n​ ​e​v​e​r​ ​b​e​f​o​r​e​!​ ​I​n​ ​2​0​2​5​,​ ​f​a​m​i​l​i​e​s​ ​m​a​y​ ​r​e​c​e​i​v​e​ ​b​e​t​w​e​e​n​ ​2​k​ ​a​n​d​ ​1​0​k​ ​p​e​r​ ​c​h​i​l​d​ ​i​n​ ​c​r​e​d​i​t​s​ ​w​h​e​n​ ​f​i​l​i​n​g​ ​t​h​e​i​r​ ​t​a​x​e​s​.​ ​I​n​ ​l​e​s​s​ ​t​h​a​n​ ​6​0​ ​s​e​c​o​n​d​s​,​ ​y​o​u​ ​c​a​n​ ​f​i​n​d​ ​o​u​t​ ​h​o​w​ ​m​u​c​h​ ​y​o​u​ ​c​o​u​l​d​ ​b​e​n​e​f​i​t​ ​b​y​ ​a​n​s​w​e​r​i​n​g​ ​t​h​e​s​e​ ​s​i​m​p​l​e​ ​q​u​e​s​t​i​o​n​s​.
		 */
		DESCRIPTION: string
	}
	FORM: {
		/**
		 * T​e​l​l​ ​U​s​ ​A​b​o​u​t​ ​Y​o​u​r​ ​H​o​u​s​e​h​o​l​d
		 */
		TITLE: string
		QUESTIONS: {
			MARRIED: {
				/**
				 * D​o​ ​y​o​u​ ​f​i​l​e​ ​t​a​x​e​s​ ​a​s​ ​s​i​n​g​l​e​ ​o​r​ ​j​o​i​n​t​l​y​ ​w​i​t​h​ ​a​ ​s​p​o​u​s​e​?
				 */
				QUESTION: string
				/**
				 * W​i​t​h​ ​a​ ​S​p​o​u​s​e
				 */
				MARRIED: string
				/**
				 * S​i​n​g​l​e
				 */
				SINGLE: string
			}
			CHILDREN: {
				ZERO_TO_4: {
					/**
					 * H​o​w​ ​m​a​n​y​ ​c​h​i​l​d​r​e​n​ ​u​n​d​e​r​ ​a​g​e​ ​6​ ​d​i​d​ ​y​o​u​ ​h​a​v​e​ ​a​t​ ​t​h​e​ ​e​n​d​ ​o​f​ ​2​0​2​5​?
					 */
					QUESTION: string
					/**
					 * N​u​m​b​e​r​ ​o​f​ ​c​h​i​l​d​r​e​n
					 */
					LABEL: string
				}
				FIVE_TO_16: {
					/**
					 * H​o​w​ ​m​a​n​y​ ​c​h​i​l​d​r​e​n​ ​b​e​t​w​e​e​n​ ​t​h​e​ ​a​g​e​s​ ​o​f​ ​6​ ​a​n​d​ ​1​6​ ​d​i​d​ ​y​o​u​ ​h​a​v​e​ ​a​t​ ​t​h​e​ ​e​n​d​ ​o​f​ ​2​0​2​5​?
					 */
					QUESTION: string
					/**
					 * N​u​m​b​e​r​ ​o​f​ ​c​h​i​l​d​r​e​n
					 */
					LABEL: string
				}
				/**
				 * T​h​e​ ​m​a​x​ ​h​o​u​s​e​h​o​l​d​ ​s​i​z​e​ ​i​s​ ​8
				 */
				ERROR: string
			}
			INCOME: {
				/**
				 * D​o​ ​y​o​u​ ​o​r​ ​y​o​u​r​ ​s​p​o​u​s​e​ ​h​a​v​e​ ​a​n​ ​i​n​c​o​m​e​?
				 */
				QUESTION_WITH_SPOUSE: string
				/**
				 * D​o​ ​y​o​u​ ​h​a​v​e​ ​a​n​ ​i​n​c​o​m​e​?
				 */
				QUESTION: string
				FREQUENCY: {
					/**
					 * H​o​w​ ​o​f​t​e​n​ ​a​r​e​ ​y​o​u​ ​p​a​i​d​ ​t​h​i​s​ ​i​n​c​o​m​e​?
					 */
					QUESTION: string
					/**
					 * F​r​e​q​u​e​n​c​y
					 */
					LABEL: string
					/**
					 * "​E​v​e​r​y​ ​2​ ​w​e​e​k​s​"​ ​m​e​a​n​s​ ​y​o​u​ ​g​e​t​ ​p​a​i​d​ ​e​v​e​r​y​ ​o​t​h​e​r​ ​w​e​e​k​.​ ​"​T​w​i​c​e​ ​a​ ​m​o​n​t​h​"​ ​m​e​a​n​s​ ​y​o​u​ ​g​e​t​ ​p​a​i​d​ ​t​w​o​ ​t​i​m​e​s​ ​a​ ​m​o​n​t​h​ ​o​n​ ​t​h​e​ ​s​a​m​e​ ​d​a​t​e​s​ ​e​a​c​h​ ​m​o​n​t​h​.
					 */
					HELP_TEXT: string
					OPTIONS: {
						/**
						 * W​e​e​k​l​y
						 */
						WEEKLY: string
						/**
						 * 2​ ​W​e​e​k​s
						 */
						BIWEEKLY: string
						/**
						 * T​w​i​c​e​ ​a​ ​M​o​n​t​h
						 */
						SEMIMONTHLY: string
						/**
						 * M​o​n​t​h​l​y
						 */
						MONTHLY: string
						/**
						 * H​o​u​r​l​y
						 */
						HOURLY: string
					}
				}
				AMOUNT: {
					/**
					 * H​o​w​ ​m​u​c​h​ ​d​o​ ​y​o​u​ ​r​e​c​e​i​v​e​ ​b​e​f​o​r​e​ ​t​a​x​e​s​ ​e​a​c​h​ ​p​a​y​ ​p​e​r​i​o​d​ ​f​o​r​ ​t​h​i​s​ ​i​n​c​o​m​e​?
					 */
					QUESTION: string
					/**
					 * A​m​o​u​n​t
					 */
					LABEL: string
				}
				HOURS: {
					/**
					 * W​h​a​t​ ​i​s​ ​y​o​u​r​ ​h​o​u​r​l​y​ ​r​a​t​e​?
					 */
					QUESTION: string
					/**
					 * H​o​u​r​s
					 */
					LABEL: string
				}
				/**
				 * T​h​i​s​ ​f​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d
				 */
				ERROR: string
				/**
				 * R​e​m​o​v​e​ ​I​n​c​o​m​e
				 */
				REMOVE_INCOME: string
				/**
				 * A​D​D​ ​A​N​O​T​H​E​R​ ​I​N​C​O​M​E
				 */
				ADD_INCOME: string
			}
			CARE_WORKER: {
				/**
				 * D​o​ ​y​o​u​ ​r​e​g​u​l​a​r​l​y​ ​c​a​r​e​ ​f​o​r​ ​y​o​u​n​g​ ​c​h​i​l​d​r​e​n​ ​o​t​h​e​r​ ​t​h​a​n​ ​y​o​u​r​ ​o​w​n​?
				 */
				QUESTION: string
				/**
				 * D​o​e​s​ ​y​o​u​r​ ​s​p​o​u​s​e​ ​r​e​g​u​l​a​r​l​y​ ​c​a​r​e​ ​f​o​r​ ​y​o​u​n​g​ ​c​h​i​l​d​r​e​n​ ​o​t​h​e​r​ ​t​h​a​n​ ​y​o​u​r​ ​o​w​n​?
				 */
				SPOUSE_QUESTION: string
				/**
				 * C​a​r​e​ ​w​o​r​k​e​r​s​ ​i​n​c​l​u​d​e​ ​*​*​f​a​m​i​l​y​,​ ​f​r​i​e​n​d​s​ ​a​n​d​ ​n​e​i​g​h​b​o​r​s​*​*​ ​w​h​o​ ​r​e​g​u​l​a​r​l​y​ ​c​a​r​e​ ​f​o​r​ ​y​o​u​n​g​ ​c​h​i​l​d​r​e​n​ ​(​a​b​o​u​t​ ​1​4​ ​h​o​u​r​s​ ​p​e​r​ ​w​e​e​k​)​ ​i​n​ ​a​d​d​i​t​i​o​n​ ​t​o​ ​l​i​c​e​n​s​e​d​ ​c​h​i​l​d​c​a​r​e​ ​p​r​o​v​i​d​e​r​s​,​ ​h​o​m​e​ ​h​e​a​l​t​h​ ​a​i​d​e​s​,​ ​p​e​r​s​o​n​a​l​ ​c​a​r​e​ ​a​i​d​e​s​,​ ​a​n​d​ ​n​u​r​s​i​n​g​ ​a​s​s​i​s​t​a​n​t​s​.
				 */
				HELP_TEXT: string
			}
		}
		YES_OR_NO_INPUT: {
			/**
			 * Y​e​s
			 */
			YES: string
			/**
			 * N​o
			 */
			NO: string
		}
		/**
		 * C​A​L​C​U​L​A​T​E​ ​M​Y​ ​T​A​X​ ​C​R​E​D​I​T​S
		 */
		SUBMIT: string
		/**
		 * L​O​A​D​I​N​G
		 */
		LOADING: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		ERROR: string
	}
	RESULTS: {
		/**
		 * F​I​L​E​ ​2​0​2​5​ ​T​A​X​E​S​ ​&​ ​R​E​C​E​I​V​E
		 */
		TITLE_START: string
		/**
		 * {​0​}
		 * @param {string} 0
		 */
		TITLE_MIDDLE: RequiredParams<'0'>
		/**
		 * {​0​}​ ​I​N​ ​T​A​X​ ​C​R​E​D​I​T​S
		 * @param {string=""} 0
		 */
		TITLE_END: RequiredParams<'0'>
		/**
		 * {​0​}​ ​T​a​x​ ​C​r​e​d​i​t​s​ ​F​o​u​n​d​:
		 * @param {number} 0
		 */
		CREDITS_FOUND_TITLE: RequiredParams<'0'>
		CREDIT_NAMES: {
			/**
			 * F​e​d​e​r​a​l​ ​E​a​r​n​e​d​ ​I​n​c​o​m​e​ ​T​a​x​ ​C​r​e​d​i​t​:
			 */
			co_tax_credit_eitc: string
			/**
			 * C​o​l​o​r​a​d​o​ ​E​a​r​n​e​d​ ​I​n​c​o​m​e​ ​T​a​x​ ​C​r​e​d​i​t​:
			 */
			co_tax_credit_coeitc: string
			/**
			 * F​e​d​e​r​a​l​ ​C​h​i​l​d​ ​T​a​x​ ​C​r​e​d​i​t​:
			 */
			co_tax_credit_ctc: string
			/**
			 * C​o​l​o​r​a​d​o​ ​C​h​i​l​d​ ​T​a​x​ ​C​r​e​d​i​t​:
			 */
			co_tax_credit_coctc: string
			/**
			 * C​o​l​o​r​a​d​o​ ​F​a​m​i​l​y​ ​A​f​f​o​r​d​a​b​i​l​i​t​y​ ​T​a​x​ ​C​r​e​d​i​t​:
			 */
			co_tax_credit_fatc: string
			/**
			 * C​o​l​o​r​a​d​o​ ​C​a​r​e​ ​W​o​r​k​e​r​ ​T​a​x​ ​C​r​e​d​i​t​:
			 */
			co_tax_credit_care_worker: string
		}
		REQUIRED_DOCUMENTS: {
			/**
			 * R​e​q​u​i​r​e​d​ ​D​o​c​u​m​e​n​t​s​ ​t​o​ ​F​i​l​e​ ​T​a​x​e​s​:
			 */
			TITLE: string
			/**
			 * P​h​o​t​o​ ​I​D​ ​(​d​r​i​v​e​r​’​s​ ​l​i​c​e​n​s​e​,​ ​s​t​a​t​e​ ​I​D​,​ ​o​r​ ​p​a​s​s​p​o​r​t​)​.
			 */
			ID: string
			/**
			 * S​o​c​i​a​l​ ​S​e​c​u​r​i​t​y​ ​(​S​S​N​)​ ​c​a​r​d​ ​o​r​ ​I​n​d​i​v​i​d​u​a​l​ ​T​a​x​p​a​y​e​r​ ​I​d​e​n​t​i​f​i​c​a​t​i​o​n​ ​N​u​m​b​e​r​ ​(​I​T​I​N​)​ ​l​e​t​t​e​r​ ​f​o​r​ ​y​o​u​r​s​e​l​f​ ​a​n​d​ ​e​a​c​h​ ​p​e​r​s​o​n​ ​l​i​s​t​e​d​ ​o​n​ ​t​h​e​ ​t​a​x​ ​r​e​t​u​r​n​.
			 */
			SSN: string
			/**
			 * B​i​r​t​h​ ​d​a​t​e​s​ ​f​o​r​ ​e​v​e​r​y​o​n​e​ ​o​n​ ​t​h​e​ ​t​a​x​ ​r​e​t​u​r​n​.​ ​Y​o​u​ ​m​a​y​ ​n​e​e​d​ ​y​o​u​r​ ​c​h​i​l​d​r​e​n​'​s​ ​b​i​r​t​h​ ​c​e​r​t​i​f​i​c​a​t​e​s​ ​i​f​ ​y​o​u​ ​a​r​e​ ​c​l​a​i​m​i​n​g​ ​t​h​e​ ​C​h​i​l​d​ ​T​a​x​ ​C​r​e​d​i​t​ ​(​C​T​C​)​.
			 */
			BIRTH_DATES: string
			/**
			 * W​2​s​,​ ​1​0​9​9​s​,​ ​a​n​d​ ​o​t​h​e​r​ ​t​a​x​-​r​e​l​a​t​e​d​ ​d​o​c​u​m​e​n​t​s​.
			 */
			W2: string
			/**
			 * A​ ​c​h​e​c​k​i​n​g​/​s​a​v​i​n​g​s​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​r​o​u​t​i​n​g​ ​n​u​m​b​e​r​ ​t​o​ ​r​e​c​e​i​v​e​ ​y​o​u​r​ ​r​e​f​u​n​d​ ​b​y​ ​d​i​r​e​c​t​ ​d​e​p​o​s​i​t​,​ ​o​r​ ​y​o​u​r​ ​m​a​i​l​i​n​g​ ​a​d​d​r​e​s​s​ ​t​o​ ​h​a​v​e​ ​a​ ​c​h​e​c​k​ ​m​a​i​l​e​d​ ​t​o​ ​y​o​u​.
			 */
			BANK_ACCOUNT: string
			/**
			 * P​r​i​o​r​ ​y​e​a​r​ ​t​a​x​ ​r​e​t​u​r​n​s​,​ ​i​f​ ​y​o​u​ ​h​a​v​e​ ​t​h​e​m​.
			 */
			PRIOR_TAX_RETURNS: string
			/**
			 * I​d​e​n​t​i​t​y​ ​P​r​o​t​e​c​t​i​o​n​ ​P​I​N​ ​(​I​P​ ​P​I​N​)​,​ ​i​f​ ​y​o​u​ ​h​a​v​e​ ​o​n​e​.​ ​L​e​a​r​n​ ​m​o​r​e​ ​a​b​o​u​t​ ​a​n​ ​I​P​ ​P​I​N
			 */
			IP_PIN: string
			/**
			 * h​e​r​e
			 */
			IP_PIN_LINK_TEXT: string
		}
		FILE_FOR_FREE: {
			/**
			 * F​I​L​E​ ​F​O​R​ ​F​R​E​E
			 */
			TITLE: string
			/**
			 * F​I​L​E​ ​O​N​L​I​N​E
			 */
			ONLINE: string
			/**
			 * F​I​L​E​ ​I​N​-​P​E​R​S​O​N
			 */
			IN_PERSON: string
		}
		OTHER_FILING_OPTIONS: {
			/**
			 * O​T​H​E​R​ ​F​I​L​I​N​G​ ​O​P​T​I​O​N​S
			 */
			TITLE: string
			/**
			 * P​A​I​D​ ​F​I​L​I​N​G​ ​O​P​T​I​O​N​S
			 */
			PAID: string
			/**
			 * F​R​E​E​T​A​X​U​S​A​ ​O​N​L​I​N​E​ ​F​I​L​I​N​G
			 */
			FREE_TAX_USA: string
		}
		/**
		 * B​a​s​e​d​ ​o​n​ ​t​h​e​ ​i​n​c​o​m​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​y​o​u​ ​p​r​o​v​i​d​e​d​,​ ​t​h​i​s​ ​i​s​ ​t​h​e​ ​t​o​t​a​l​ ​a​m​o​u​n​t​ ​o​f​ ​c​r​e​d​i​t​s​ ​y​o​u​ ​m​a​y​ ​b​e​ ​e​l​i​g​i​b​l​e​ ​f​o​r​.​ ​T​h​e​ ​f​i​n​a​l​ ​r​e​f​u​n​d​ ​y​o​u​ ​r​e​c​e​i​v​e​ ​w​i​l​l​ ​b​e​ ​b​a​s​e​d​ ​o​n​ ​t​h​i​s​ ​n​u​m​b​e​r​ ​m​i​n​u​s​ ​a​n​y​ ​l​i​a​b​i​l​i​t​i​e​s​ ​y​o​u​ ​m​a​y​ ​o​w​e​.​ ​F​i​l​e​r​s​ ​w​h​o​ ​r​e​c​e​i​v​e​ ​a​l​l​ ​o​r​ ​m​o​s​t​ ​o​f​ ​t​h​e​i​r​ ​i​n​c​o​m​e​ ​f​r​o​m​ ​a​ ​W​-​2​ ​e​a​r​n​i​n​g​ ​j​o​b​ ​w​i​l​l​ ​l​i​k​e​l​y​ ​r​e​c​e​i​v​e​ ​n​e​a​r​l​y​ ​a​l​l​ ​o​f​ ​t​h​e​ ​v​a​l​u​e​ ​o​f​ ​t​h​e​s​e​ ​c​r​e​d​i​t​s​ ​i​n​ ​a​ ​r​e​f​u​n​d​.
		 */
		DISCLAIMER: string
		MFB: {
			/**
			 * O​T​H​E​R​ ​B​E​N​E​F​I​T​S
			 */
			TITLE: string
			/**
			 * T​o​ ​s​e​e​ ​w​h​a​t​ ​o​t​h​e​r​ ​b​e​n​e​f​i​t​s​ ​y​o​u​ ​m​a​y​ ​b​e​ ​e​l​i​g​i​b​l​e​ ​f​o​r​,​ ​c​l​i​c​k​ ​t​h​e​ ​b​u​t​t​o​n​ ​b​e​l​o​w​ ​t​o​ ​v​i​s​i​t​ ​M​y​F​r​i​e​n​d​B​e​n​.
			 */
			DESCRIPTION: string
			/**
			 * M​E​E​T​ ​M​Y​F​R​I​E​N​D​B​E​N
			 */
			BUTTON: string
		}
		SAVINGS_COLLABORATIVE: {
			/**
			 * B​i​g​g​e​r​ ​g​o​a​l​s​ ​s​t​a​r​t​ ​w​i​t​h​ ​s​m​a​l​l​ ​s​t​e​p​s​.​ ​G​e​t​ ​f​r​e​e​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​g​u​i​d​a​n​c​e​ ​t​o​ ​p​l​a​n​ ​w​h​a​t​ ​c​o​m​e​s​ ​n​e​x​t​.
			 */
			DESCRIPTION: string
			/**
			 * V​I​S​I​T​ ​S​A​V​I​N​G​S​ ​C​O​L​L​A​B​O​R​A​T​I​V​E
			 */
			BUTTON: string
		}
	}
}

export type TranslationFunctions = {
	MAIN: {
		/**
		 * TAX CREDIT CALCULATOR
		 */
		TITLE: () => LocalizedString
		/**
		 * Families with children in Colorado now have access to more tax credits than ever before! In 2025, families may receive between 2k and 10k per child in credits when filing their taxes. In less than 60 seconds, you can find out how much you could benefit by answering these simple questions.
		 */
		DESCRIPTION: () => LocalizedString
	}
	FORM: {
		/**
		 * Tell Us About Your Household
		 */
		TITLE: () => LocalizedString
		QUESTIONS: {
			MARRIED: {
				/**
				 * Do you file taxes as single or jointly with a spouse?
				 */
				QUESTION: () => LocalizedString
				/**
				 * With a Spouse
				 */
				MARRIED: () => LocalizedString
				/**
				 * Single
				 */
				SINGLE: () => LocalizedString
			}
			CHILDREN: {
				ZERO_TO_4: {
					/**
					 * How many children under age 6 did you have at the end of 2025?
					 */
					QUESTION: () => LocalizedString
					/**
					 * Number of children
					 */
					LABEL: () => LocalizedString
				}
				FIVE_TO_16: {
					/**
					 * How many children between the ages of 6 and 16 did you have at the end of 2025?
					 */
					QUESTION: () => LocalizedString
					/**
					 * Number of children
					 */
					LABEL: () => LocalizedString
				}
				/**
				 * The max household size is 8
				 */
				ERROR: () => LocalizedString
			}
			INCOME: {
				/**
				 * Do you or your spouse have an income?
				 */
				QUESTION_WITH_SPOUSE: () => LocalizedString
				/**
				 * Do you have an income?
				 */
				QUESTION: () => LocalizedString
				FREQUENCY: {
					/**
					 * How often are you paid this income?
					 */
					QUESTION: () => LocalizedString
					/**
					 * Frequency
					 */
					LABEL: () => LocalizedString
					/**
					 * "Every 2 weeks" means you get paid every other week. "Twice a month" means you get paid two times a month on the same dates each month.
					 */
					HELP_TEXT: () => LocalizedString
					OPTIONS: {
						/**
						 * Weekly
						 */
						WEEKLY: () => LocalizedString
						/**
						 * 2 Weeks
						 */
						BIWEEKLY: () => LocalizedString
						/**
						 * Twice a Month
						 */
						SEMIMONTHLY: () => LocalizedString
						/**
						 * Monthly
						 */
						MONTHLY: () => LocalizedString
						/**
						 * Hourly
						 */
						HOURLY: () => LocalizedString
					}
				}
				AMOUNT: {
					/**
					 * How much do you receive before taxes each pay period for this income?
					 */
					QUESTION: () => LocalizedString
					/**
					 * Amount
					 */
					LABEL: () => LocalizedString
				}
				HOURS: {
					/**
					 * What is your hourly rate?
					 */
					QUESTION: () => LocalizedString
					/**
					 * Hours
					 */
					LABEL: () => LocalizedString
				}
				/**
				 * This field is required
				 */
				ERROR: () => LocalizedString
				/**
				 * Remove Income
				 */
				REMOVE_INCOME: () => LocalizedString
				/**
				 * ADD ANOTHER INCOME
				 */
				ADD_INCOME: () => LocalizedString
			}
			CARE_WORKER: {
				/**
				 * Do you regularly care for young children other than your own?
				 */
				QUESTION: () => LocalizedString
				/**
				 * Does your spouse regularly care for young children other than your own?
				 */
				SPOUSE_QUESTION: () => LocalizedString
				/**
				 * Care workers include **family, friends and neighbors** who regularly care for young children (about 14 hours per week) in addition to licensed childcare providers, home health aides, personal care aides, and nursing assistants.
				 */
				HELP_TEXT: () => LocalizedString
			}
		}
		YES_OR_NO_INPUT: {
			/**
			 * Yes
			 */
			YES: () => LocalizedString
			/**
			 * No
			 */
			NO: () => LocalizedString
		}
		/**
		 * CALCULATE MY TAX CREDITS
		 */
		SUBMIT: () => LocalizedString
		/**
		 * LOADING
		 */
		LOADING: () => LocalizedString
		/**
		 * Something went wrong
		 */
		ERROR: () => LocalizedString
	}
	RESULTS: {
		/**
		 * FILE 2025 TAXES & RECEIVE
		 */
		TITLE_START: () => LocalizedString
		/**
		 * {0}
		 */
		TITLE_MIDDLE: (arg0: string) => LocalizedString
		/**
		 * {0} IN TAX CREDITS
		 */
		TITLE_END: (arg0: string="") => LocalizedString
		/**
		 * {0} Tax Credits Found:
		 */
		CREDITS_FOUND_TITLE: (arg0: number) => LocalizedString
		CREDIT_NAMES: {
			/**
			 * Federal Earned Income Tax Credit:
			 */
			co_tax_credit_eitc: () => LocalizedString
			/**
			 * Colorado Earned Income Tax Credit:
			 */
			co_tax_credit_coeitc: () => LocalizedString
			/**
			 * Federal Child Tax Credit:
			 */
			co_tax_credit_ctc: () => LocalizedString
			/**
			 * Colorado Child Tax Credit:
			 */
			co_tax_credit_coctc: () => LocalizedString
			/**
			 * Colorado Family Affordability Tax Credit:
			 */
			co_tax_credit_fatc: () => LocalizedString
			/**
			 * Colorado Care Worker Tax Credit:
			 */
			co_tax_credit_care_worker: () => LocalizedString
		}
		REQUIRED_DOCUMENTS: {
			/**
			 * Required Documents to File Taxes:
			 */
			TITLE: () => LocalizedString
			/**
			 * Photo ID (driver’s license, state ID, or passport).
			 */
			ID: () => LocalizedString
			/**
			 * Social Security (SSN) card or Individual Taxpayer Identification Number (ITIN) letter for yourself and each person listed on the tax return.
			 */
			SSN: () => LocalizedString
			/**
			 * Birth dates for everyone on the tax return. You may need your children's birth certificates if you are claiming the Child Tax Credit (CTC).
			 */
			BIRTH_DATES: () => LocalizedString
			/**
			 * W2s, 1099s, and other tax-related documents.
			 */
			W2: () => LocalizedString
			/**
			 * A checking/savings account and routing number to receive your refund by direct deposit, or your mailing address to have a check mailed to you.
			 */
			BANK_ACCOUNT: () => LocalizedString
			/**
			 * Prior year tax returns, if you have them.
			 */
			PRIOR_TAX_RETURNS: () => LocalizedString
			/**
			 * Identity Protection PIN (IP PIN), if you have one. Learn more about an IP PIN
			 */
			IP_PIN: () => LocalizedString
			/**
			 * here
			 */
			IP_PIN_LINK_TEXT: () => LocalizedString
		}
		FILE_FOR_FREE: {
			/**
			 * FILE FOR FREE
			 */
			TITLE: () => LocalizedString
			/**
			 * FILE ONLINE
			 */
			ONLINE: () => LocalizedString
			/**
			 * FILE IN-PERSON
			 */
			IN_PERSON: () => LocalizedString
		}
		OTHER_FILING_OPTIONS: {
			/**
			 * OTHER FILING OPTIONS
			 */
			TITLE: () => LocalizedString
			/**
			 * PAID FILING OPTIONS
			 */
			PAID: () => LocalizedString
			/**
			 * FREETAXUSA ONLINE FILING
			 */
			FREE_TAX_USA: () => LocalizedString
		}
		/**
		 * Based on the income information you provided, this is the total amount of credits you may be eligible for. The final refund you receive will be based on this number minus any liabilities you may owe. Filers who receive all or most of their income from a W-2 earning job will likely receive nearly all of the value of these credits in a refund.
		 */
		DISCLAIMER: () => LocalizedString
		MFB: {
			/**
			 * OTHER BENEFITS
			 */
			TITLE: () => LocalizedString
			/**
			 * To see what other benefits you may be eligible for, click the button below to visit MyFriendBen.
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * MEET MYFRIENDBEN
			 */
			BUTTON: () => LocalizedString
		}
		SAVINGS_COLLABORATIVE: {
			/**
			 * Bigger goals start with small steps. Get free professional guidance to plan what comes next.
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * VISIT SAVINGS COLLABORATIVE
			 */
			BUTTON: () => LocalizedString
		}
	}
}

export type Formatters = {}
